#!/usr/bin/env python
import sys
__actions = ("pca")

def main():
    if len(sys.argv) == 1 or sys.argv[1] in ("-h", "--help"):
        print >>sys.stderr,"""
View and find correlations in your clinical and lab data.

   Contact: Brent Pedersen - bpederse@gmail.com
   License: BSD

To run, indicate one of:

SEE: https://github.com/brentp/clinical-components for documentation
    """
        sys.exit()
    else:
        module = getattr(__import__('clinco', fromlist=[sys.argv[1]]), sys.argv[1])
        # remove the action
        sys.argv.pop(1)
        module.main()

if __name__ == "__main__":
    main()
